### ISSUE TITLE
sbatch: command not found

### ISSUE THREAD

**Issue by Alice-302** [orrzohar/FOMO#10]
When I execute ./configs/run_rwd.sh, an error message appears: ./configs/run_rwd.sh: line 54: sbatch: command not found
How to solve it?
![image](https://github.com/orrzohar/FOMO/assets/144978346/8312f346-8560-4673-b937-712fb018a185)

**Comment by orrzohar** [comment]
Hi @Alice-302,

These configs are for a slurm cluster. You are supposed to update your partition/account etc, or just use the python commands if you are not using slurm 

Best,
Orr

**Comment by Alice-302** [comment]
> Hi @Alice-302,
> 
> These configs are for a slurm cluster. You are supposed to update your partition/account etc, or just use the python commands if you are not using slurm
> 
> Best, Orr

Thank you for your prompt reply.
Sorry,I don’t quite understand how to use python commands to run,There is no executable python command in[configs/run_rwd.sh](https://github.com/orrzohar/FOMO/blob/6df2dca8e9f051261dc7be89d5a8ece4f2642515/configs/run_rwd.sh)

**Comment by orrzohar** [comment]
Hi @Alice-302,

The python command can be found:

https://github.com/orrzohar/FOMO/blob/6df2dca8e9f051261dc7be89d5a8ece4f2642515/configs/run_rwd.sh#L45-L49

The bash for-loops over the different datasets and configurations to allow one to run all datasets on multiple GPUs simultaneously.

Best,
Orr

**Comment by Alice-302** [comment]
Hi @orrzohar 
First of all, thank you for your patient answer.
Is it possible to train without slurm cluster if I use the following command?
This is the code I run, does it have any effect on the results?
##!/bin/bash

set -e
cur_fname="$(basename $0 .sh)"
script_name=$(basename $0)


partition=""
account=""
save_dict="tmp/imagenet/t_1"


TCP_INIT=29500
counter=0


declare -a DATASETS=("Aerial" "Surgical" "Medical" "Aquatic" "Game")
declare -a MODELS=("google/owlvit-base-patch16" "google/owlvit-large-patch14")
declare  -a UNK_CLASS_FILES=("None" "unknown_classnames_ground_truth.txt" "unknown_classnames_imagenet.txt" "unknown_classnames.txt")



declare -A CUR_INTRODUCED_CLS
CUR_INTRODUCED_CLS["Aerial"]=10
CUR_INTRODUCED_CLS["Surgical"]=6
CUR_INTRODUCED_CLS["Medical"]=6
CUR_INTRODUCED_CLS["Aquatic"]=4
CUR_INTRODUCED_CLS["Game"]=30

declare -A BATCH_SIZEs
BATCH_SIZEs["google/owlvit-base-patch16"]=4
BATCH_SIZEs["google/owlvit-large-patch14"]=2

declare -A IMAGE_SIZEs
IMAGE_SIZEs["google/owlvit-base-patch16"]=768
IMAGE_SIZEs["google/owlvit-large-patch14"]=840


for unk_class_file in "${UNK_CLASS_FILES[@]}"; do
  for dataset in "${DATASETS[@]}"; do
    cur_cls=${CUR_INTRODUCED_CLS[$dataset]}
    for model in "${MODELS[@]}"; do
      BATCH_SIZE=${BATCH_SIZEs[$model]}
      IMAGE_SIZE=${IMAGE_SIZEs[$model]}
      tcp=$((TCP_INIT + counter))

      
      cmd="python main.py --model_name \"$model\" --batch_size $BATCH_SIZE \
      --PREV_INTRODUCED_CLS 0 --CUR_INTRODUCED_CLS $cur_cls --TCP $tcp --dataset $dataset \
      --image_resize $IMAGE_SIZE --unknown_classnames_file $unk_class_file --unk_proposal  \
      --unk_methods 'None' --unk_method 'None'"
      ##--output_dir $save_dict"  --output_file $model-$dataset-$unk_class_file.csv"

      echo "Constructed Command: $cmd"

      
      eval "$cmd"

      counter=$((counter + 1))
    done
  done
done

**Comment by orrzohar** [comment]
Hi @Alice-302,
I think this should run! You don't need the TCP port/counter as you will be running sequentially. 
Best,
Orr
