### ISSUE TITLE
NeuroSurgicalTools dataset download failed

### ISSUE THREAD

**Issue by YH-2023** [orrzohar/FOMO#11]
When I download the NeuroSurgicalTools dataset, I need to log in to the website. However, I am not in the institution, so I cannot download NeuroSurgicalTools.zip. Is there any way to release the dataset?

**Comment by orrzohar** [comment]
hi @YH-2023,

You do not need to log in or anything -- here is the download link:
https://ged.univ-rennes1.fr/nuxeo/nxfile/default/1f25b055-2b0d-4cca-82b3-64d05f7268ad/blobholder:0/NeuroSurgicalToolsDataset.zip

LMK if that works for you,
Orr

**Comment by YH-2023** [comment]
> hi @YH-2023,
> 
> You do not need to log in or anything -- here is the download link: https://ged.univ-rennes1.fr/nuxeo/nxfile/default/1f25b055-2b0d-4cca-82b3-64d05f7268ad/blobholder:0/NeuroSurgicalToolsDataset.zip
> 
> LMK if that works for you, Orr

Thank you very much for your prompt reply

**Comment by YH-2023** [comment]
Hi @orrzohar 
When training the OWD task, executing the [./configs/run_owd_baseline.sh](https://github.com/orrzohar/FOMO/blob/6df2dca8e9f051261dc7be89d5a8ece4f2642515/configs/run_owd_baseline.sh) command, should I execute [open_world.py](https://github.com/orrzohar/FOMO/blob/6df2dca8e9f051261dc7be89d5a8ece4f2642515/datasets/torchvision_datasets/open_world.py) or [real_world.py](https://github.com/orrzohar/FOMO/blob/6df2dca8e9f051261dc7be89d5a8ece4f2642515/datasets/torchvision_datasets/real_world.py)? However, when I execute  [open_world.py](https://github.com/orrzohar/FOMO/blob/6df2dca8e9f051261dc7be89d5a8ece4f2642515/datasets/torchvision_datasets/open_world.py), 
I get an error:
  File "/home/FOMO/datasets/open_world_eval.py", line 44, in __init__
    self.unknown_class_index = len(voc_gt.KNOWN_CLASS_NAMES)
AttributeError: 'OWDetection' object has no attribute 'KNOWN_CLASS_NAMES'
