### ISSUE TITLE
ImageSets

### ISSUE THREAD

**Issue by rolsheng** [orrzohar/FOMO#2]
I have download five datasets and reorgnize them into `data/RWD` following your instruction.  But I found that the number of images for each dataset cannot match your train/test split in `data/ImageSets/*/train.txt or test.txt`. Do you select the part of original images for each dataset to setup RWD benchmark? 

Looking forward your reply! @orrzohar

**Comment by orrzohar** [comment]
Hi @rolsheng,
I looked and only saw that in the Aquatic dataset, the test dataset is not filtered correctly (I will be updating that now such that there are no "train" images in the "test" file).

Have you noticed any other issues?

Best,
Orr

**Comment by rolsheng** [comment]
Alright, I will conduct some experiment on RWD benchmark soon and disuss if have other issues. Thanks!

**Comment by orrzohar** [comment]
Hi @rolsheng,
I have updated the file.
Let me know if you find another issue with the dataset, or if this was not the issue you had originally.
Best,
Orr

**Comment by rolsheng** [comment]
> Hi @rolsheng, I looked and only saw that in the Aquatic dataset, the test dataset is not filtered correctly (I will be updating that now such that there are no "train" images in the "test" file).
> 
> Have you noticed any other issues?
> 
> Best, Orr

Alright, I will conduct some experiment on RWD benchmark soon and disuss if have other issues. Thanks!
