### ISSUE TITLE
The domain variable issue in gen_attributes.ipynb

### ISSUE THREAD

**Issue by lnq325805524** [orrzohar/FOMO#3]
First of all, thank you for the very impressive work. 

While working with gen_attributes.ipynb to generate attributes, I've noticed that only the 'medical' dataset has a corresponding domain variable, specifically 'xray images of the bones in the hands.' I was wondering if you could kindly provide guidance on how to specify the domain information for the other datasets (Aquatic, Aerial, Game, Surgery)? Your assistance would be greatly appreciated.

**Comment by orrzohar** [comment]
Hi @lnq325805524,
I didn't really keep track of that; I don't believe it is too critical. I used something like:
1. Aquatic: Underwater images of different animals.
2. Aerial: arial/satellite images.
3. Game: Video game screenshots of different characters.
4. Medical: Xray images of the bones in the hands.
5. Surgical: Neuro microscopy images of different surgical tools.
Best,
Orr

**Comment by lnq325805524** [comment]
Got it. Thanks for your reply.
