### ISSUE TITLE
about training

### ISSUE THREAD

**Issue by xxyzll** [orrzohar/FOMO#7]
Hello, I currently have only one machine but it has two graphics cards. How should I modify the code to train on such a machine?

**Comment by orrzohar** [comment]
Hi @xxyzll,

Training doesn't really take that long, but if you want, I would follow the distributed framework I have here:

https://github.com/orrzohar/PROB/tree/main

Specifically you can use this file: 

https://github.com/orrzohar/PROB/blob/main/tools/run_dist_launch.sh

Note you will need to add two main.py a similar line such as this:

https://github.com/orrzohar/PROB/blob/28afbc1d7f5bdfb9a384ce09c870fcd829adc1b2/main_open_world.py#L172C1-L173C1
